version: '3.8'

networks:
  java-data-connect:
    driver: bridge

volumes:
  mysql_vol:


services:
  java-task-list:
      image: joaoinvernal/task-list-api:v3
      ports:
        - 8080:8080
      networks:
        - java-data-connect
      depends_on:
        - mysql-base

  mysql-base:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - java-data-connect
    volumes:
      - mysql_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql12344
      MYSQL_DATABASE: datafort



---
##docker run --name mysql-base -e MYSQL_ROOT_PASSWORD=mysql12344 -e MYSQL_DATABAS=datafort -p 3306:3306 --network java-data-connect mysql
##docker run --name java-task-app -p 8080:8080 --network java-data-connect task-list-api:v1
