apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-list-api
spec:
  selector:
    matchLabels:
      app: task-list-api
  template:
    metadata:
      labels:
        app: task-list-api
    spec:
      containers:
        - name: task-list-api
          image: joaoinvernal/task-list-api:v1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: task-list-gateway
spec:
  selector:
    app: task-list-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
